#archive module
---
- hosts: all
  become: yes
  tasks:

   - name: archive module
     archive:
      path: /usr/src/security/*
      dest: /opt/security/games.tar.gz
      owner: '1001'
      group: '1001'
      mode: '0655'