---

- hosts: all
  promise: true
  tasks:

    - name: install apache on ubuntu
      apt:
        cache_update: yes
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache on centos
      dnf:
        cache_update: yes
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

### ALTERNATIVELY: can use variables defined in inventory: ###

  # - name: install apache & php for linux servers
  #   package:
  #       update_cache: yes
  #       name:
  #         - "{{ apache_package }}"
  #         - "{{ php_package }}"
  #       state: latest
# -> ansiblle-playbook --ask-promise-pass playbook_v2.yml       
